### ISSUE TITLE
1.1.0 fails to load grammar

### ISSUE THREAD

**Issue by kerryb** [craigw/dns-zonefile#11]
When I load the gem, I get the following error:

    $ pry
    [1] pry(main)> require "dns/zonefile"
    Errno::ENOENT: No such file or directory @ rb_sysopen - lib/dns/zonefile.treetop
    from /Users/kerry/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/treetop-1.6.5/lib/treetop/compiler/grammar_compiler.rb:37:in `initialize'

It looks like this is a load path issue, as if I edit the gem source to expand the full path of `zonefile.treetop` the error disappears.

**Comment by craigw** [comment]
Thanks @kerryb, I'll take a look at this now. Sorry for the inconvenience!

**Comment by craigw** [comment]
This should be fixes with 1.1.2. Can you please try with that version and re-open this issue if I've not managed to fix it for you? Thanks for opening the issue :)
