### ISSUE TITLE
Remove parser.rb from source control?

### ISSUE THREAD

**Issue by aeden** [craigw/dns-zonefile#9]
Is it possible to remove parser.rb from source control since it is a generated file? It is very hard to apply upstream changes, or supply clean, sensible PRs, with potential conflicts in this generated file.

**Comment by craigw** [comment]
Hi @aeden,

Totally up for that. Do you have some ideas for how that could be done while still making using the gem really simple? I'd love to see PRs with suggestions.

Cheers,
Craig

**Comment by aeden** [comment]
Craig, have a look at https://github.com/craigw/dns-zonefile/pull/10 and let me know what you think.

**Comment by craigw** [comment]
Fixed by #10.
